Way 1/Method 1:
<div class="header-account">
<div class="toggle-tab">
<span class="header-icon user"></span>
<strong><?php echo __('Hello') ?></strong>
<?php echo __(', Sign in') ?>
</div>
<div class="toggle-content">
<?php echo $this->getChildHtml('header.links'); ?>
</div>
</div>

Way 2/Method 1:
<?php echo $this->getChildHtml('account.links'); ?>
/home/wp2cart/web/wp2cart.com/public_html/biolife/app/design/frontend/Alothemes/*/Magento_Theme/templates/html/account.phtml