<div class="blog-category">
                                <div class="post-info clear">
                                    <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <div class="dash">|</div>
                                    <div class="item post-categories">
                                        <span class="label"><?php echo __('Categories:') ?></span>
                                        <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
                                        <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>"
                                            href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                                        <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                                        <?php } ?>
                                    </div>
                                    <?php } ?>
                                </div>
                            </div>